package db

const (
	ORDER_STATUS_DISPUTE OrderStatusCode = iota - 4
	ORDER_STATUS_NOT_DELIVERED
	ORDER_STATUS_NOT_ACCEPTED
	ORDER_STATUS_NOT_PAID
	ORDER_STATUS_NEW
	ORDER_STATUS_PAID
	ORDER_STATUS_ACCEPTED
	ORDER_STATUS_DELIVERED
	ORDER_STATUS_FULFILLED
)

const (
	PRODUCT_STATUS_NEW ProductStatusCode = iota
	PRODUCT_STATUS_UNAVAILABLE
	PRODUCT_STATUS_APPROVED
	PRODUCT_STATUS_NOT_APPROVED
)

const (
	SUPPLIER_STATUS_BLOCKED SupplierStatusCode = iota - 1
	SUPPLIER_STATUS_INACTIVE
	SUPPLIER_STATUS_ACTIVE
)

const (
	PERMISSION_HISTORY Permission = 1 << iota
	PERMISSION_MOBILE_APP
	PERMISSION_DELIVERY_OPTIONS
	PERMISSION_ORDERS
	PERMISSION_PRODUCTS_CATALOGUE
	PERMISSION_CONTENT_FILTERING
	PERMISSION_STATISTICS
	PERMISSION_CATEGORIES_DIRECTORY
	PERMISSION_SUPPLIERS_REGISTER
	PERMISSION_ACCOUNT_MANAGEMENT
	PERMISSION_ADMINISTRATION
)

const (
	ROLE_PASSENGER RoleID = iota
	ROLE_MEDIATOR
	ROLE_SUPPLIER
	ROLE_MODERATOR
	ROLE_ADMINISTRATOR
)
